Rampage/Areas/Admin/Controllers/BlogController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Rampage.Areas.Admin.Utilities.Helpers;
using Rampage.Areas.Admin.Utilities.Services;
using Rampage.Database;
using Rampage.Database.DomainModels;
using Rampage.ViewModels;

namespace Rampage.Areas.Admin.Controllers;
[Area("Admin")]
[Authorize(Roles = "Admin")]
public class BlogController : Controller
{
    private readonly AppDbContext _context;
    private readonly CloudinaryService _cloudinaryService;
    public BlogController(AppDbContext context, CloudinaryService cloudinaryService)
    {
        _context = context;
        _cloudinaryService = cloudinaryService;
    }

    public async Task<IActionResult> Index()
    {
        var blogs = await _context.Blogs.Include(x => x.BlogCategory).ToListAsync();
        return View(blogs);
    }

    public async Task<IActionResult> Create()
    {
        var categories = await _context.BlogCategories.ToListAsync();
        ViewBag.Categories = categories;
        return View();
    }
    [HttpPost]
    public async Task<IActionResult> Create(BlogPostVM vm)
    {
        var categories = await _context.BlogCategories.ToListAsync();
        ViewBag.Categories = categories;

        if (!ModelState.IsValid)
            return View(vm);

        var isExistCategory = categories.Any(x => x.Id == vm.BlogCategoryId);
        if (!isExistCategory)
        {
            ModelState.AddModelError("BlogCategoryId", "Burda bir yanlışlık var.");
            return View(vm);
        }

        if (!vm.Image.ValidateImage(2))
        {
            ModelState.AddModelError("Image", "Resim doğru formatda ve boyutu 2 mb dan az olmalıdır");
            return View(vm);
        }

        Blog blog = new()
        {
            Name = vm.Name,
            Description = vm.Description,
            BlogCategoryId = vm.BlogCategoryId,
            ImagePath = await _cloudinaryService.FileCreateAsync(vm.Image),
            CreatedTime = DateTime.UtcNow
        };


        await _context.Blogs.AddAsync(blog);
        await _context.SaveChangesAsync();

        return RedirectToAction("Index");
    }

    public async Task<IActionResult> Update(int id)
    {
        var blog = await _context.Blogs.FirstOrDefaultAsync(x => x.Id == id);

        if (blog is null)
            return NotFound();

        var categories = await _context.BlogCategories.ToListAsync();
        ViewBag.Categories = categories;


        BlogPutVM vm = new()
        {
            Id=id,
            Name=blog.Name,
            Description=blog.Description,
            ImagePath=blog.ImagePath,
            BlogCategoryId=blog.BlogCategoryId,

        };

        return View(vm);

    }

    [HttpPost]
    public async Task<IActionResult> Update(BlogPutVM vm)
    {

        var categories = await _context.BlogCategories.ToListAsync();
        ViewBag.Categories = categories;


        if (!ModelState.IsValid)
            return View(vm);

        var existBlog = await _context.Blogs.FirstOrDefaultAsync(x => x.Id == vm.Id);

        if (existBlog is null)
            return NotFound();

        var isExistCategory = categories.Any(x => x.Id == vm.BlogCategoryId);
        if (!isExistCategory)
        {
            ModelState.AddModelError("BlogCategoryId", "Burda bir yanlışlık var.");
            return View(vm);
        }

        if (vm.Image is not null && !vm.Image.ValidateImage(2))
        {
            ModelState.AddModelError("Image", "Resim doğru formatda ve boyutu 2 mb dan az olmalıdır");
            return View(vm);
        }


        existBlog.Name=vm.Name;
        existBlog.Description=vm.Description;
        existBlog.BlogCategoryId = vm.BlogCategoryId;

        if (vm.Image is not null)
            existBlog.ImagePath = await _cloudinaryService.FileCreateAsync(vm.Image);

        _context.Blogs.Update(existBlog);
        await _context.SaveChangesAsync();


        return RedirectToAction("Index");
    }


    public async Task<IActionResult> Delete(int id)
    {
        var blog=await _context.Blogs.FirstOrDefaultAsync(x=>x.Id == id);

        if(blog is null)
            return NotFound();

        _context.Blogs.Remove(blog);
        await _context.SaveChangesAsync();


        return RedirectToAction("Index");
    }


    public async Task<IActionResult> Detail(int id)
    {
        var blog = await _context.Blogs.Include(x=>x.BlogCategory).FirstOrDefaultAsync(x => x.Id == id);

        if (blog is null)
            return NotFound();

        return View(blog);
    }




}

Rampage/Controllers/BlogController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Rampage.Database;
using Rampage.ViewModels;

namespace Rampage.Controllers;

public class BlogController : Controller
{
    private readonly AppDbContext _context;

    public BlogController(AppDbContext context)
    {
        _context = context;
    }

    public async Task<IActionResult> Index(int? id)
    {

        var query = _context.Blogs.AsQueryable();
        if (id is not null)
        {
            if (!await _context.BlogCategories.AnyAsync(x => x.Id == id))
                return NotFound();
            query = query.Where(x => x.BlogCategoryId == id);
        }
        var blogs=await query.ToListAsync();    
        var recentBlogs = await _context.Blogs.OrderByDescending(x=>x.Id).Take(2).ToListAsync();
        var categories = await _context.BlogCategories.Include(x=>x.Blogs).ToListAsync();

        BlogVM vm = new()
        { BlogCategories = categories, Blogs = blogs ,RecentBlogs=recentBlogs};


        return View(vm);
    }


    public async Task<IActionResult> Detail(int id)
    {
        var blog = await _context.Blogs.FirstOrDefaultAsync(x => x.Id == id);
        if (blog is null)
            return NotFound();

        var categories = await _context.BlogCategories.Include(x => x.Blogs).ToListAsync();


        BlogDetailVM vm = new()
        {
            Blog = blog,
            BlogCategories = categories,
        };

        return View(vm);
    }
}

Rampage/Views/Blog/Detail.cshtml
@model BlogDetailVM
<main>
    <section class="about-main-container">
        <div class="main-box-item03">
            <div class="blog-categories-all">
                <div class="into-blog-cate">
                    <div class="blog-cate-title">
                        <img src="/assets/image/news-icon.png" alt="Rampage Logo">
                        <span>Kategoriler</span>
                    </div>

                    <div class="blog-list">
                        <ul>

                            <li>
                                <a asp-action="Index" asp-controller="Blog" asp-route-id="@null">
                                    <span class="news-cont"></span>
                                    <span>Tümü</span>
                                </a>
                            </li>
                            @foreach (var category in Model.BlogCategories)
                            {
                                <li>
                                    <a asp-action="Index" asp-controller="Blog" asp-route-id="@category.Id">
                                        <span class="news-cont">@category.Blogs.Count</span>
                                        <span>@category.Name</span>
                                    </a>
                                </li>

                            }

                        </ul>
                    </div>

                </div>
            </div>
        </div>

        <div class="main-box-item02">
            <div class="header">
                <div class="header-icon">
                    <svg xmlns="http://www.w3.org/2000/svg" width="10.151" height="15" viewBox="0 0 10.151 15">
                        <path d="M6.824,0H2.288C-.344,0-.547,2.366.874,3.654l7.364,6.692C9.66,11.634,9.456,14,6.824,14H2.288C-.344,14-.547,11.634.874,10.346L8.238,3.654C9.66,2.366,9.456,0,6.824,0Z"
                              transform="translate(0.519 0.5)"></path>
                    </svg>
                </div>
                <span>@Model.Blog.CreatedTime.ToString().Substring(0, 10)</span>
            </div>
            <div class="title">
                <h2>
                    @Model.Blog.Name
                </h2>
            </div>
            <div class="cnt">
                <p>

                </p>
            </div>
            <div class="content">
                <img src="@Model.Blog.ImagePath" alt="">
            </div>
            <div class="text-content">
                <p>
                    @Model.Blog.Description
                </p>


                <p>Keyifli oyunlar dileriz!</p>

                <p>Rampage Ekibi</p>
            </div>
        </div>
        <div class="main-box-item01">
            <div class="contact-box-1">
                <i class="fa-solid fa-share-nodes"></i>
                <span>Paylaş</span>
            </div>
            <div class="contact-icon">
                <a href="#"><i class="fa-brands fa-facebook"></i></a>
                <a href="#"><i class="fa-brands fa-twitter"></i></a>
                <a href="#"><i class="fa-brands fa-telegram"></i></a>
                <a href="#"><i class="fa-brands fa-linkedin"></i></a>
                <a href="#"><i class="fa-brands fa-whatsapp"></i></a>
            </div>
        </div>
    </section>
</main>

Rampage/Views/Blog/Index.cshtml
@model BlogVM
<main>
    <section class="title-news-box">
        <div class="title-news-box-container">
            <div class="news-title">
                <span>En Son Neler Yaşandı?</span>
            </div>
            <div class="news-boxs">
                @foreach (var blog in Model.RecentBlogs)
                {
                    <div class="news-box" style="margin-right:10px">
                        <div class="news-category">
                            <span>@blog.BlogCategory.Name</span>
                        </div>
                        <div class="news-text">
                            <h3>@blog.Name</h3>
                        </div>
                        <div class="news-date">
                            <span>Paylaşım Tarihi</span>
                            <div class="date-line"></div>
                            <p>@blog.CreatedTime.ToString().Substring(0,10)</p>
                        </div>
                    </div>
                }

            </div>
        </div>
    </section>
    <section class="blog-container">
        <div class="blog-share-all">
            <div class="blog-share">
                <div class="blog-share-title">
                    <h3>Önceki Paylaşımlar</h3>
                </div>
                @foreach (var blog in Model.Blogs)
                {
                    <div class="blog-image-text" style="margin-bottom:20px">
                        <div class="blog-image">
                            <a href="#">
                                <img src="@blog.ImagePath" alt="BlogShare">
                            </a>
                        </div>
                        <div class="blog-text">
                            <div class="blog-date">
                                <span>@blog.CreatedTime.ToString().Substring(0,10)</span>
                            </div>
                            <div class="blog-content">
                                <a href="#">
                                    <h3>@blog.Name</h3>
                                </a>
                            </div>
                            <div class="blog-cnt">
                                <p>
                                  @blog.Description
                                </p>
                            </div>
                        </div>
                    </div>
                }
            </div>
            <div class="blog-categories-all">
                <div class="into-blog-cate">
                    <div class="blog-cate-title">
                        <img src="~/assets/image/news-icon.png" alt="Rampage Logo">
                        <span>Kategoriler</span>
                    </div>

                    <div class="blog-list">
                        <ul>

                            <li>
                                <a asp-action="Index" asp-controller="Blog" asp-route-id="@null">
                                    <span class="news-cont"></span>
                                    <span>Tümü</span>
                                </a>
                            </li>
                            @foreach (var category in Model.BlogCategories)
                            {
                                <li>
                                    <a asp-action="Index" asp-controller="Blog" asp-route-id="@category.Id">
                                        <span class="news-cont">@category.Blogs.Count</span>
                                        <span>@category.Name</span>
                                    </a>
                                </li>

                            }

                        </ul>
                    </div>

                </div>
            </div>
        </div>
    </section>
</main>



<script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js"></script>
<script src="~/assets/js/blog.js"></script>